name: devops CI/CD

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Build project with Maven
      run: mvn -B package --file backend/pom.xml

  publish-job:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - run: mvn -B package --file backend/pom.xml
      - run: mkdir staging && cp -r backend/target/*.jar staging
      - uses: actions/upload-artifact@v1
        with:
          name: Package
          path: staging
  SCA:
    name: Scurity Scanner
    runs-on: ubuntu-latest
    needs: [publish-job]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: install archerysec 
        run: pip install archerysec-cli --force --ignore-installed six
      - name: run dependency check scan through archerysec
        run: |
          cd staging && archerysec-cli -h ${ARCHERYSEC_HOST} -t ${ARCHERYSEC_TOKEN} --cicd_id=345311ce-be68-45b1-b5e8-6c8e8e239028 --project=29b9ce74-f2c7-417d-af7d-4de2d8f810c3 --dependency-check --report_path=$(pwd)

        env:
          ARCHERYSEC_HOST: ${{ secrets.ARCHERYSEC_HOST }}
          ARCHERYSEC_USER: ${{ secrets.ARCHERYSEC_TOKEN }}
         







          