name: devops CI/CD

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Build project with Maven
      run: mvn -B package --file backend/pom.xml

  publish-job:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - run: mvn -B package --file backend/pom.xml
      - run: mkdir staging && cp -r backend/target/*.jar staging
      - uses: actions/upload-artifact@v1
        with:
          name: Package
          path: staging

  SCA:
    name: Scurity Scanner
    runs-on: ubuntu-latest
    needs: [publish-job]
    container:
      image: archerysec/dependency-check
    steps:
      - name: Check out artifacts
        uses: actions/download-artifact@v1
        with:
          name: Package
          path: staging
      - name: install archerysec 
        run: pip install archerysec-cli --force --ignore-installed six
        
      - name: run zap baseline scan
        run: '--scan /src --format "ALL" --project "dependency-check scan: staging" --out /report'

      - name: run dependency check scan through archerysec
        run: |
          archerysec-cli -h http://54.211.100.97 -t GjnSo-99yta1u7o9-7MQw2KKxaQSICkxFo1f2e159zH0AvzhKtVEa_9jodpUPa8J -p /report/dependency-check-report.xml  --file-type=XML --target=sadfasdfsaf --scanner=dependencycheck --project=503b2dc4-d431-47ef-b0a5-d664745c4c85 --upload
  
  DAST:
    runs-on: ubuntu-latest
    needs: [build]
    container:
      image: archerysec/owasp-zap
      options: --user root -v ${{ github.workspace }}:/zap/wrk/
    steps:
      - name: install archerysec 
        run:  pip install archerysec-cli --force --ignore-installed six 
      - name: run zap baseline scan
        run: zap-baseline.py -t https://archerysec.com -x report_xml.xml || echo 0
      - name: run zap scan through archerysec
        run: |
          archerysec-cli -h http://54.211.100.97 -t GjnSo-99yta1u7o9-7MQw2KKxaQSICkxFo1f2e159zH0AvzhKtVEa_9jodpUPa8J -p report_xml.xml  --file-type=XML --target=ASFLKSF --scanner=zap_scan --project=503b2dc4-d431-47ef-b0a5-d664745c4c85 --upload

          
  
    







          